abstract class EnterYourInformationStates{}

class EnterYourInformationInitialState extends EnterYourInformationStates{}

class ImagePickerLoadingState extends EnterYourInformationStates{}
class ImagePickerSuccessfullyState extends EnterYourInformationStates{}
class ImagePickerErrorState extends EnterYourInformationStates{}

class UploadUserDataLoadingState extends EnterYourInformationStates{}
class UploadUserDataSuccessfullyState extends EnterYourInformationStates{}
class UploadUserDataErrorState extends EnterYourInformationStates{}